### ISSUE TITLE
Unexpected peer dependency?

### ISSUE THREAD

**Issue by targos** [SamVerschueren/listr#91]
It seems like the latest version (0.14.0) introduced a new peer dependency.
I get this error when I try to load `listr` in a new project:

```
$ node -p "require('listr')"
/home/targos/test/node_modules/any-observable/register.js:29
		throw new Error('Cannot find any-observable implementation nor' +
		^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/home/targos/test/node_modules/any-observable/register.js:29:9)
    at register (/home/targos/test/node_modules/any-observable/loader.js:32:18)
    at Object.<anonymous> (/home/targos/test/node_modules/any-observable/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
```

**Comment by marcuspoehls** [comment]
@targos Same here. Did you solve it?

**Comment by targos** [comment]
@marcuspoehls no. I'm staying on v0.13.0 for now.

**Comment by SamVerschueren** [comment]
It's due to this bug in `any-observable` https://github.com/sindresorhus/any-observable/issues/18. Hope to get this fixed shortly after the weekend.

**Comment by moehlone** [comment]
fix is out with sindresorhus/any-observable/releases/tag/v0.3.0

**Comment by Rawnly** [comment]
Same here on `^0.14.0`

**Comment by SamVerschueren** [comment]
Still waiting on `stream-to-observable`. Use an 0.13 for now, sorry for the inconvenience. If it isn't merged at the beginning of next week, I'll fork the package so we can fix this.

**Comment by marcuspoehls** [comment]
Wow, great work Sam!

Thank you for keeping us updated and working on a fix yourself.
You are awesome ❤️

**Comment by SamVerschueren** [comment]
Still finishing up some details. Hope to get this fixed tomorrow.

**Comment by SamVerschueren** [comment]
`listr@0.14.1` is released and should fix this issue (hopefully).

**Comment by brunolemos** [comment]
Still getting this with 0.14.1. I'm using lint-staged (https://github.com/okonet/lint-staged/issues/416).

```
/Users/brunolemos/Projects/x/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/register.js:29
		throw new Error('Cannot find any-observable implementation nor' +
		^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/Users/brunolemos/Projects/x/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/register.js:29:9)
    at /Users/brunolemos/Projects/x/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/loader.js:30:18
    at Object.<anonymous> (/Users/brunolemos/Projects/x/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/index.js:2:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by brunolemos** [comment]
Fixed by deleting both node_modules and package-lock.json.

**Comment by davidtheclark** [comment]
I'm also running into this problem with 0.14.1. And I cannot seem to get around it, despite wiping my caches and all the locks and `node_modules` and so on. So this is making lint-staged unusable for me on a certain project :( 

Here are my relevant dependency versions:

```
└─┬ lint-staged@7.2.0
    └─┬ listr@0.14.1
      └─┬ @samverschueren/stream-to-observable@0.3.0
        └── any-observable@0.3.0
````

**Comment by aleclarson** [comment]
Could `lint-staged` fix this by depending on `zen-observable` or `rxjs` itself?

I'm running into this after installing `lint-staged` with PNPM [(see here)](https://github.com/pnpm/pnpm/issues/1496).

- `lint-staged@8.0.5`
- `listr@0.14.2`

**Comment by DanMat** [comment]
Facing a similar issue with `v0.14.3` and using `rollup` to bundle my project.

```
Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
```

I ended up installing [`any-observable`](https://www.npmjs.com/package/any-observable) and polyfilling it with [`rollup-plugin-polyfill`](https://www.npmjs.com/package/rollup-plugin-polyfill)

```
{
	input: 'bin/cli.js',
	output: {
		file: 'dist/bundle.cjs.js',
		format: 'cjs',
		strict: false,
		banner: '#! /usr/bin/env node\n',
	},
	plugins: [
		...,
		polyfill(['any-observable/register/rxjs']),
		...
	]
}
